/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SUDIP
 */
public class ExamArea extends javax.swing.JFrame {

    /**
     * Creates new form ExamArea
     */
        Connection connect = null;
        ResultSet rst=null;
        PreparedStatement pst=null;
    public ExamArea() {
        initComponents();
            this.setLocationRelativeTo(null);
            connect=connectDB.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcourse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jquestion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ja1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ja = new javax.swing.JRadioButton();
        jb1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jb = new javax.swing.JRadioButton();
        jc1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jc = new javax.swing.JRadioButton();
        jd1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jd = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane3.setViewportView(jEditorPane1);

        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EXAM AREA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Course : ");

        jcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course", "C", "C++", "C#", "PYTHON", "RUBY", "PERL", "JAVA", "JAVA SCRIPT", "VISUAL BASIC", "PHP", "SQL", " " }));
        jcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcourseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Question : ");

        jquestion.setColumns(20);
        jquestion.setForeground(new java.awt.Color(0, 0, 153));
        jquestion.setRows(5);
        jScrollPane1.setViewportView(jquestion);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Select appropriate answer from following : ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Next >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("a)");

        ja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ja1Layout = new javax.swing.GroupLayout(ja1);
        ja1.setLayout(ja1Layout);
        ja1Layout.setHorizontalGroup(
            ja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ja1Layout.setVerticalGroup(
            ja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ja))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("b)");

        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jb1Layout = new javax.swing.GroupLayout(jb1);
        jb1.setLayout(jb1Layout);
        jb1Layout.setHorizontalGroup(
            jb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jb1Layout.setVerticalGroup(
            jb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jb))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("c)");

        jc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jc1Layout = new javax.swing.GroupLayout(jc1);
        jc1.setLayout(jc1Layout);
        jc1Layout.setHorizontalGroup(
            jc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jc1Layout.setVerticalGroup(
            jc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jc1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jc))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("d)");

        jd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd1Layout = new javax.swing.GroupLayout(jd1);
        jd1.setLayout(jd1Layout);
        jd1Layout.setHorizontalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd1Layout.setVerticalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jd))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Click on \" Sbmit\" button before click on \"Next\" button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
            .addComponent(ja1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(135, 135, 135)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcourseActionPerformed
        // TODO add your handling code here:
       
                String sql = "select * from question_info where course= ?";
        try
        {
            pst = connect.prepareStatement(sql);
            pst.setString(1,jcourse.getSelectedItem().toString());
            rst = pst.executeQuery();
            if (rst.next())
            {
                jquestion.setText(rst.getString("question"));
                ja.setText(rst.getString("option_a"));
                jb.setText(rst.getString("option_b"));
                jc.setText(rst.getString("option_c"));
                jd.setText(rst.getString("option_d"));
                
                        ja1.setBackground(new Color(240, 240,240));
                        jb1.setBackground(new Color(240, 240,240));
                        jc1.setBackground(new Color(240, 240,240));
                        jd1.setBackground(new Color(240, 240,240));
                        
            }
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcourseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                ja.setSelected(false);
                jb.setSelected(false);
                jc.setSelected(false);
                jd.setSelected(false);
                        ja1.setBackground(new Color(240, 240,240));
                        jb1.setBackground(new Color(240, 240,240));
                        jc1.setBackground(new Color(240, 240,240));
                        jd1.setBackground(new Color(240, 240,240));
       
        try
        {
  
            if(rst.next())
            {
                    jquestion.setText(rst.getString("question"));
                    ja.setText(rst.getString("option_a"));
                    jb.setText(rst.getString("option_b"));
                    jc.setText(rst.getString("option_c"));
                    jd.setText(rst.getString("option_d"));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "You already attempted all questions!! \n Now click on 'Exit' button to know your score!!");
            }

        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
                ip="127.0.0.1";
                c1=new Socket(ip, 2005);
                brc=new BufferedReader(new InputStreamReader(c1.getInputStream()));
                out=new PrintWriter(c1.getOutputStream(),true);//auto flush
                r=new ExamArea.ReadThread();
                r.start();
                out.println(g);
                setTitle("Client Window ["+g+"]");
                JOptionPane.showMessageDialog(null, "Your score is : "+g);
                System.exit(0);
        }catch(HeadlessException | IOException e){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaActionPerformed
        // TODO add your handling code here:
        if(ja.isSelected())
        {
            jb.setSelected(false);
            jc.setSelected(false);
            jd.setSelected(false);
            store=ja.getText();
             ja1.setBackground(new Color(152, 251, 152));
             jb1.setBackground(new Color(240, 240,240));
             jc1.setBackground(new Color(240, 240,240));
             jd1.setBackground(new Color(240, 240,240));
        }
    }//GEN-LAST:event_jaActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
        // TODO add your handling code here:
                if(jb.isSelected())
        {
            ja.setSelected(false);
            jc.setSelected(false);
            jd.setSelected(false);
            store=jb.getText();
             jb1.setBackground(new Color(152, 251, 152));
             ja1.setBackground(new Color(240, 240,240));
             jc1.setBackground(new Color(240, 240,240));
             jd1.setBackground(new Color(240, 240,240));
        }
    }//GEN-LAST:event_jbActionPerformed

    private void jcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcActionPerformed
        // TODO add your handling code here:
                if(jc.isSelected())
        {
            ja.setSelected(false);
            jb.setSelected(false);
            jd.setSelected(false);
            store=jc.getText();
             jc1.setBackground(new Color(152, 251, 152));
             ja1.setBackground(new Color(240, 240,240));
             jb1.setBackground(new Color(240, 240,240));
             jd1.setBackground(new Color(240, 240,240));
        }
    }//GEN-LAST:event_jcActionPerformed

    private void jdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdActionPerformed
        // TODO add your handling code here:
                if(jd.isSelected())
        {
            ja.setSelected(false);
            jb.setSelected(false);
            jc.setSelected(false);
            store=jd.getText();
             jd1.setBackground(new Color(152, 251, 152));
             ja1.setBackground(new Color(240, 240,240));
             jb1.setBackground(new Color(240, 240,240));
             jc1.setBackground(new Color(240, 240,240));
        }
    }//GEN-LAST:event_jdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                ja.setSelected(false);
                jb.setSelected(false);
                jc.setSelected(false);
                jd.setSelected(false);
                        ja1.setBackground(new Color(240, 240,240));
                        jb1.setBackground(new Color(240, 240,240));
                        jc1.setBackground(new Color(240, 240,240));
                        jd1.setBackground(new Color(240, 240,240));
                        JOptionPane.showMessageDialog(null,"Your ans sucessfully submit \nNow click on 'Next' button for next question");
        try{
                      if(store == null ? rst.getString("ans") == null : store.equals(rst.getString("ans")))
                         {
                             g=g+Integer.parseInt(rst.getString("marks"));
                         }  
                      
  
            
        }catch( NumberFormatException | SQLException e)
        {}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton ja;
    private javax.swing.JPanel ja1;
    private javax.swing.JRadioButton jb;
    private javax.swing.JPanel jb1;
    private javax.swing.JRadioButton jc;
    private javax.swing.JPanel jc1;
    private javax.swing.JComboBox<String> jcourse;
    private javax.swing.JRadioButton jd;
    private javax.swing.JPanel jd1;
    private javax.swing.JTextArea jquestion;
    // End of variables declaration//GEN-END:variables
            String store=null;
            public static int g=0;
        private Socket c1;
        private BufferedReader brc;
        private PrintWriter out;
        private String ip;
        private ReadThread r;
        class ReadThread extends Thread
            {
            @Override
            public void run()
                {
                }
            }
}
